// <auto-generated />
using System;
using GrandLineAuto.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GrandLineAuto.Data.Migrations
{
    [DbContext(typeof(GrandLineAutoDbContext))]
    partial class GrandLineAutoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GrandLineAuto.Data.Models.Brand", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Id for brand");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Image for logo");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Name of brand");

                    b.HasKey("Id");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3f6c9c77-4c1b-4d2b-9df2-1e8e4c27bba4"),
                            ImageUrl = "https://blog.logomaster.ai/hs-fs/hubfs/bmw-logo-1963.jpg?width=672&height=454&name=bmw-logo-1963.jpg",
                            Name = "BMW"
                        },
                        new
                        {
                            Id = new Guid("9b2f1c3d-2f50-4c4c-b4ce-0f7d7f2c9f61"),
                            ImageUrl = "https://static.vecteezy.com/system/resources/previews/020/499/027/non_2x/mercedes-benz-brand-logo-symbol-white-with-name-design-german-car-automobile-illustration-with-black-background-free-vector.jpg",
                            Name = "Mercedes-Benz"
                        },
                        new
                        {
                            Id = new Guid("c4c8a1c9-7c29-4d47-8c19-3e9d2ef0be55"),
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ae/Logo_audi.jpg/960px-Logo_audi.jpg",
                            Name = "Audi"
                        },
                        new
                        {
                            Id = new Guid("0a7cb569-2e0e-4c76-a28e-92e3d355fa28"),
                            ImageUrl = "https://images.seeklogo.com/logo-png/16/1/porsche-logo-png_seeklogo-168544.png",
                            Name = "Porsche"
                        });
                });

            modelBuilder.Entity("GrandLineAuto.Data.Models.BrandModelProductJoinTable", b =>
                {
                    b.Property<Guid>("BrandModelId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Mapping to brand model");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Mapping to product");

                    b.HasKey("BrandModelId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("BrandModelProductJoinTables");

                    b.HasData(
                        new
                        {
                            BrandModelId = new Guid("4e8c1f22-9d4b-4f36-a7c1-2b9f53d1e8aa"),
                            ProductId = new Guid("f4a9d0c2-8b11-4e35-b6f2-9c7a1d54e820")
                        },
                        new
                        {
                            BrandModelId = new Guid("9cbf2146-7c33-4a51-9f2c-41e7a4d92bb8"),
                            ProductId = new Guid("f4a9d0c2-8b11-4e35-b6f2-9c7a1d54e820")
                        },
                        new
                        {
                            BrandModelId = new Guid("31c4e0aa-9f12-4b0d-8f7e-55a1cb2d7c44"),
                            ProductId = new Guid("7e24b1c9-3a5f-44d0-9e72-0c1fb78d4aa3")
                        },
                        new
                        {
                            BrandModelId = new Guid("7de41fa8-1c26-4f3e-9d72-04c9fd8a33b7"),
                            ProductId = new Guid("7e24b1c9-3a5f-44d0-9e72-0c1fb78d4aa3")
                        });
                });

            modelBuilder.Entity("GrandLineAuto.Data.Models.BrandModels", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Id for brand model");

                    b.Property<Guid>("BrandModelsSeriesId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Belongs to a serie");

                    b.Property<string>("Engine")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasComment("Engine");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Image of the model");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Name for given model");

                    b.Property<string>("fuelType")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)")
                        .HasComment("Fuel type");

                    b.Property<string>("typeCoupe")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)")
                        .HasComment("Type of coupe");

                    b.Property<int>("yearProduced")
                        .HasColumnType("int")
                        .HasComment("Year the car is produced");

                    b.HasKey("Id");

                    b.HasIndex("BrandModelsSeriesId");

                    b.ToTable("BrandModels");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4e8c1f22-9d4b-4f36-a7c1-2b9f53d1e8aa"),
                            BrandModelsSeriesId = new Guid("e2f3b6c1-9c4d-4c88-86b8-7f92b1e4a6d2"),
                            Engine = "320i",
                            ImageUrl = "https://img-ik.cars.co.za/images/2022/12Dec/E90BMW3SeriesSedanBuyersGuide/tr:n-news_large/2007-m3-sedan-2.jpg?tr=w-800",
                            Name = "E90",
                            fuelType = "Petrol",
                            typeCoupe = "Sedan",
                            yearProduced = 2007
                        },
                        new
                        {
                            Id = new Guid("31c4e0aa-9f12-4b0d-8f7e-55a1cb2d7c44"),
                            BrandModelsSeriesId = new Guid("e2f3b6c1-9c4d-4c88-86b8-7f92b1e4a6d2"),
                            Engine = "335i",
                            ImageUrl = "https://www.automoli.com/common/vehicles/_assets/img/gallery/f98/bmw-3-series-convertible-e93-lci-facelift-2010.jpg",
                            Name = "E93",
                            fuelType = "Petrol",
                            typeCoupe = "Cabrio",
                            yearProduced = 2009
                        },
                        new
                        {
                            Id = new Guid("f1a7c0d4-35b2-4c88-8c9d-0a7e1f54b6d3"),
                            BrandModelsSeriesId = new Guid("c2f7d914-5b8a-4e3d-92b4-1af08c7e33a1"),
                            Engine = "5.0 V10 Naturally aspirated",
                            ImageUrl = "https://www.secretentourage.com/wp-content/uploads/2014/12/cover.jpg",
                            Name = "E60 M5",
                            fuelType = "Petrol",
                            typeCoupe = "Sedan",
                            yearProduced = 2010
                        },
                        new
                        {
                            Id = new Guid("9cbf2146-7c33-4a51-9f2c-41e7a4d92bb8"),
                            BrandModelsSeriesId = new Guid("4a0dbf77-2e3a-4c1f-a1c9-3e2df59482b3"),
                            Engine = "320 CDI",
                            ImageUrl = "https://i0.wp.com/bestsellingcarsblog.com/wp-content/uploads/2011/06/Mercedes-C-Class-Germany-2008.jpg?resize=600%2C344&ssl=1",
                            Name = "Mercedes-Benz C320",
                            fuelType = "Diesel",
                            typeCoupe = "Sedan",
                            yearProduced = 2007
                        },
                        new
                        {
                            Id = new Guid("0fa2e9d1-4e8b-4c76-bf33-9a2d6c107be9"),
                            BrandModelsSeriesId = new Guid("4a0dbf77-2e3a-4c1f-a1c9-3e2df59482b3"),
                            Engine = "C63 AMG",
                            ImageUrl = "https://car-images.bauersecure.com/wp-images/12978/1mercedesc63amgdrive.jpg",
                            Name = "Mercedes-Benz C63",
                            fuelType = "Petrol",
                            typeCoupe = "Sedan",
                            yearProduced = 2010
                        },
                        new
                        {
                            Id = new Guid("7de41fa8-1c26-4f3e-9d72-04c9fd8a33b7"),
                            BrandModelsSeriesId = new Guid("a8c1f4eb-6b5a-4c9e-94df-1b3c7f8e2190"),
                            Engine = "320 CDI",
                            ImageUrl = "https://media.carsandbids.com/cdn-cgi/image/width=2080,quality=70/da4b9237bacccdf19c0760cab7aec4a8359010b0/photos/xlWuI-DUMXN2-2.0r28NUnna.jpg?t=161221805027",
                            Name = "Mercedes-Benz E320",
                            fuelType = "Diesel",
                            typeCoupe = "Sedan",
                            yearProduced = 2008
                        },
                        new
                        {
                            Id = new Guid("82f7a4c9-53d9-4ef0-8c11-7b3fd95a2c10"),
                            BrandModelsSeriesId = new Guid("a8c1f4eb-6b5a-4c9e-94df-1b3c7f8e2190"),
                            Engine = "550 AMG",
                            ImageUrl = "https://www.magnatuning.com/images/Mercedes-E-Class-W211-Exclusive-Body-Kit_picture_48790.jpg",
                            Name = "Mercedes-Benz E550",
                            fuelType = "Petrol",
                            typeCoupe = "Sedan",
                            yearProduced = 2009
                        },
                        new
                        {
                            Id = new Guid("3bd17af4-9c81-4bcd-a0c0-251f7c8d9476"),
                            BrandModelsSeriesId = new Guid("67f3c8d2-1af4-4e5d-9d10-8a3e72c6c4aa"),
                            Engine = "3.0 TDI",
                            ImageUrl = "https://7cars.bg/wp-content/uploads/2025/02/1-copy-1.jpg",
                            Name = "Audi A6 3.0",
                            fuelType = "Diesel",
                            typeCoupe = "Sedan",
                            yearProduced = 2013
                        },
                        new
                        {
                            Id = new Guid("b2c4f8a3-ef52-4b98-9da2-38c1f4c7e212"),
                            BrandModelsSeriesId = new Guid("67f3c8d2-1af4-4e5d-9d10-8a3e72c6c4aa"),
                            Engine = "3.0 TDI",
                            ImageUrl = "https://hips.hearstapps.com/hmg-prod/amv-prod-cad-assets/images/11q3/409394/2012-audi-a6-avant-tdi-diesel-review-car-and-driver-photo-411689-s-original.jpg?fill=1:1&resize=1200:*",
                            Name = "Audi A6 3.0",
                            fuelType = "Diesel",
                            typeCoupe = "Wagon",
                            yearProduced = 2015
                        },
                        new
                        {
                            Id = new Guid("6a7fc1d9-325e-4a99-8b13-cdb42f75e610"),
                            BrandModelsSeriesId = new Guid("d91ce0f5-7af1-4b78-a28e-f56e4c1c92bb"),
                            Engine = "3.0 TDI",
                            ImageUrl = "https://www.automobile-catalog.com/img/pictonorzw/audi/audi_a8070013_117.jpg",
                            Name = "Audi A8",
                            fuelType = "Diesel",
                            typeCoupe = "Sedan",
                            yearProduced = 2007
                        },
                        new
                        {
                            Id = new Guid("c8f3d27a-14a0-4c8b-94b7-1fa9c4d5e3c2"),
                            BrandModelsSeriesId = new Guid("d91ce0f5-7af1-4b78-a28e-f56e4c1c92bb"),
                            Engine = "4.2 FSI V8",
                            ImageUrl = "https://www.netcarshow.com/Audi-A8_L-2008-Rear_Three-Quarter.970bbea1.jpg",
                            Name = "Audi A8L",
                            fuelType = "Petrol",
                            typeCoupe = "Sedan",
                            yearProduced = 2008
                        },
                        new
                        {
                            Id = new Guid("0d9e3f11-b78c-47fa-b1c5-a4c2f59d8e17"),
                            BrandModelsSeriesId = new Guid("3b4f2a17-665d-43ee-bac8-0e3f4d92bb10"),
                            Engine = "4.8L V8",
                            ImageUrl = "https://smartcdn.gprod.postmedia.digital/driving/wp-content/uploads/2013/10/7607683.jpg",
                            Name = "Porsche Panamera GTS",
                            fuelType = "Petrol",
                            typeCoupe = "Sedan",
                            yearProduced = 2012
                        },
                        new
                        {
                            Id = new Guid("e41b0c92-0fd2-49e3-a9cb-708e5d34b126"),
                            BrandModelsSeriesId = new Guid("f88c3d66-2c44-4c84-9a55-64b1c385f7ae"),
                            Engine = "3.8L",
                            ImageUrl = "https://media.carsandbids.com/cdn-cgi/image/width=2080,quality=70/7a0a3c6148108c9c64425dd85e0181fa3cccb652/photos/vqhXN-hxQ.XHngqM4HaJ.jpg?t=161354154263",
                            Name = "Porsche 911 Carrera S",
                            fuelType = "Petrol",
                            typeCoupe = "Coupe",
                            yearProduced = 2006
                        });
                });

            modelBuilder.Entity("GrandLineAuto.Data.Models.BrandModelsSeries", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Identifier of Series");

                    b.Property<Guid>("BrandId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Identifier to belonged brand");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Image of Series");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Name of Series");

                    b.Property<string>("productionYears")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)")
                        .HasComment("Year of the Series");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.ToTable("BrandModelsSeries");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e2f3b6c1-9c4d-4c88-86b8-7f92b1e4a6d2"),
                            BrandId = new Guid("3f6c9c77-4c1b-4d2b-9df2-1e8e4c27bba4"),
                            ImageUrl = "https://cdn3.focus.bg/autodata/i/bmw/3er/3er-e90/large/ef6298b9bf11a376c37eebb71bd96c77.jpg",
                            Name = "BMW E90-3",
                            productionYears = "2004-2012"
                        },
                        new
                        {
                            Id = new Guid("c2f7d914-5b8a-4e3d-92b4-1af08c7e33a1"),
                            BrandId = new Guid("3f6c9c77-4c1b-4d2b-9df2-1e8e4c27bba4"),
                            ImageUrl = "https://cdn3.focus.bg/autodata/i/bmw/m5/m5-e60/large/20a25cb2b439604fe5db3c205f7e11b5.jpg",
                            Name = "BMW E60-2",
                            productionYears = "2004-2010"
                        },
                        new
                        {
                            Id = new Guid("4a0dbf77-2e3a-4c1f-a1c9-3e2df59482b3"),
                            BrandId = new Guid("9b2f1c3d-2f50-4c4c-b4ce-0f7d7f2c9f61"),
                            ImageUrl = "https://automoto.bg/listings/media/listing//1708102204_1708033948_1.jpg",
                            Name = "Mercedes-Benz C classe",
                            productionYears = "2006-2012"
                        },
                        new
                        {
                            Id = new Guid("a8c1f4eb-6b5a-4c9e-94df-1b3c7f8e2190"),
                            BrandId = new Guid("9b2f1c3d-2f50-4c4c-b4ce-0f7d7f2c9f61"),
                            ImageUrl = "https://mobistatic3.focus.bg/mobile/photosorg/536/1/big//11755160806701536_rv.webp",
                            Name = "Mercedes-Benz E classe",
                            productionYears = "2005-2010"
                        },
                        new
                        {
                            Id = new Guid("67f3c8d2-1af4-4e5d-9d10-8a3e72c6c4aa"),
                            BrandId = new Guid("c4c8a1c9-7c29-4d47-8c19-3e9d2ef0be55"),
                            ImageUrl = "https://images.ctfassets.net/uaddx06iwzdz/2KRO0CKDLDQnp38hfmbkpq/b63ce3731355495d119623ac742df6fc/audi-a6-l-01.jpg",
                            Name = "Audi A6 Serie",
                            productionYears = "2011-2017"
                        },
                        new
                        {
                            Id = new Guid("d91ce0f5-7af1-4b78-a28e-f56e4c1c92bb"),
                            BrandId = new Guid("c4c8a1c9-7c29-4d47-8c19-3e9d2ef0be55"),
                            ImageUrl = "https://media.ed.edmunds-media.com/audi/a8/2008/oem/2008_audi_a8_sedan_l-quattro_fq_oem_2_1600.jpg",
                            Name = "Audi A8 Serie",
                            productionYears = "2006-2010"
                        },
                        new
                        {
                            Id = new Guid("3b4f2a17-665d-43ee-bac8-0e3f4d92bb10"),
                            BrandId = new Guid("0a7cb569-2e0e-4c76-a28e-92e3d355fa28"),
                            ImageUrl = "https://media.drive.com.au/obj/tx_q:50,rs:auto:1920:1080:1/driveau/upload/cms/uploads/vdfiilc13rajkg86q3ps",
                            Name = "Porsche Panamera",
                            productionYears = "2009-2015"
                        },
                        new
                        {
                            Id = new Guid("f88c3d66-2c44-4c84-9a55-64b1c385f7ae"),
                            BrandId = new Guid("0a7cb569-2e0e-4c76-a28e-92e3d355fa28"),
                            ImageUrl = "https://porschepictures.flowcenter.de/pmdb/thumbnail.cgi?id=252983&w=1935&h=1089&crop=1&public=1&cs=0e7eaa33c7c2d827",
                            Name = "Porsche 911",
                            productionYears = "2004-2012"
                        });
                });

            modelBuilder.Entity("GrandLineAuto.Data.Models.CartEntities.CartItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId", "ProductId")
                        .IsUnique();

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("GrandLineAuto.Data.Models.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Identifier of category");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Image of the category");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Name of category");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5a3d9c41-7f2b-4e8c-9c31-0fb28d74a922"),
                            ImageUrl = "https://www.autopower.bg/images/categories/%D0%A1%D0%BF%D0%B8%D1%80%D0%B0%D1%87%D0%BD%D0%B0%20%D1%81%D0%B8%D1%81%D1%82%D0%B5%D0%BC%D0%B0.jpg",
                            Name = "Braking System"
                        },
                        new
                        {
                            Id = new Guid("d4f0a8c7-12b9-4c53-8d77-61f4b3e2c915"),
                            ImageUrl = "https://www.autopower.bg/images/categories/%D0%A7%D0%B0%D1%81%D1%82%D0%B8%20%D0%B7%D0%B0%20%D0%B4%D0%B2%D0%B8%D0%B3%D0%B0%D1%82%D0%B5%D0%BB.jpg",
                            Name = "Engine Parts"
                        });
                });

            modelBuilder.Entity("GrandLineAuto.Data.Models.OrderEntities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("GrandLineAuto.Data.Models.OrderEntities.OrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("GrandLineAuto.Data.Models.OrderEntities.ShippingAddress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AddressLine1")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("AddressLine2")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.ToTable("ShippingAddresses");
                });

            modelBuilder.Entity("GrandLineAuto.Data.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Identifier of product");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(650)
                        .HasColumnType("nvarchar(650)")
                        .HasComment("Information about the product");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Image of the product");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Name of product");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasComment("Price of the product");

                    b.Property<Guid>("ProductManufacturerId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Each product have manufacturer");

                    b.Property<string>("SpecificInfo1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Information about the product");

                    b.Property<string>("SpecificInfo2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Information about the product");

                    b.Property<string>("SpecificInfo3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Information about the product");

                    b.Property<string>("SpecificInfo4")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Information about the product");

                    b.Property<string>("SpecificInfo5")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Information about the product");

                    b.Property<string>("SpecificInfo6")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Information about the product");

                    b.Property<Guid>("SubCategoryId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("It has sub categories");

                    b.HasKey("Id");

                    b.HasIndex("ProductManufacturerId");

                    b.HasIndex("SubCategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f4a9d0c2-8b11-4e35-b6f2-9c7a1d54e820"),
                            Description = "Brembo Xtra: the perfect brake pad for Brembo Xtra and Brembo Max brake discs.",
                            ImageUrl = "https://www.autopower.bg/images/%D0%BD%D0%B0%D0%BA%D0%BB%D0%B0%D0%B4%D0%BA%D0%B8-BREMBO-XTRA-LINE-P06036X-BMW-3-Cabrio-E93-330-i-imagetabig-845520901733463-BREMBO.jpg",
                            Name = "Brembo XTRA LINE P 06 036X",
                            Price = 225.45m,
                            ProductManufacturerId = new Guid("2c9f4b17-63e1-4e8a-8f5c-91d2a7b6c014"),
                            SpecificInfo1 = "Installation side: Front axle",
                            SpecificInfo2 = "width [mm]: 155mm",
                            SpecificInfo3 = "thickness [mm]: 20mm",
                            SpecificInfo4 = "height [mm]: 64mm",
                            SpecificInfo5 = "",
                            SpecificInfo6 = "",
                            SubCategoryId = new Guid("a3f79de2-58c4-49e8-9b6b-e24fdc81f927")
                        },
                        new
                        {
                            Id = new Guid("7e24b1c9-3a5f-44d0-9e72-0c1fb78d4aa3"),
                            Description = "The specific drilling of Brembo Xtra brake discs provides a brilliant and efficient performance in any braking condition, to emphasise the driving style of true enthusiasts.",
                            ImageUrl = "https://www.autopower.bg/images/%D1%81%D0%BF%D0%B8%D1%80%D0%B0%D1%87%D0%B5%D0%BD-%D0%B4%D0%B8%D1%81%D0%BA-BREMBO-XTRA-LINE-Xtra-0997931X-BMW-3-Sedan-E90-320-i-imagetabig-845520901699346-BREMBO.jpg",
                            Name = "Brembo XTRA Line - Xtra",
                            Price = 240.5m,
                            ProductManufacturerId = new Guid("2c9f4b17-63e1-4e8a-8f5c-91d2a7b6c014"),
                            SpecificInfo1 = "Brake disc thickness [mm]:   20mm",
                            SpecificInfo2 = "height [mm]: 66mm",
                            SpecificInfo3 = "centering diameter [mm]: 75mm",
                            SpecificInfo4 = "outer diameter [mm]: 300mm",
                            SpecificInfo5 = "processing:  high-carbon",
                            SpecificInfo6 = "",
                            SubCategoryId = new Guid("0be4c29f-3f11-4a88-bd42-89e1cf72d4a3")
                        });
                });

            modelBuilder.Entity("GrandLineAuto.Data.Models.ProductManufacturer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Identifier of manufacturer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Name of the manufacturer");

                    b.HasKey("Id");

                    b.ToTable("ProductManufacturers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2c9f4b17-63e1-4e8a-8f5c-91d2a7b6c014"),
                            Name = "Brembo"
                        },
                        new
                        {
                            Id = new Guid("b18e57d4-0fa2-41e3-9c42-7d3f1a8ce5b9"),
                            Name = "Metzger autotelie"
                        },
                        new
                        {
                            Id = new Guid("94a0c6e3-2b71-4d8f-9f3e-0c8d27ab14d2"),
                            Name = "Febi bilstein"
                        });
                });

            modelBuilder.Entity("GrandLineAuto.Data.Models.SubCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Identifier of subCategory");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Identifier of the category");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Image of the subCategory");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Name of the subCategory");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("SubCategories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0be4c29f-3f11-4a88-bd42-89e1cf72d4a3"),
                            CategoryId = new Guid("5a3d9c41-7f2b-4e8c-9c31-0fb28d74a922"),
                            ImageUrl = "https://www.autopower.bg/images/categories/75x75/%D0%A1%D0%BF%D0%B8%D1%80%D0%B0%D1%87%D0%BD%D0%B8%20%D0%B4%D0%B8%D1%81%D0%BA%D0%BE%D0%B2%D0%B5.jpg",
                            Name = "Brake discs"
                        },
                        new
                        {
                            Id = new Guid("a3f79de2-58c4-49e8-9b6b-e24fdc81f927"),
                            CategoryId = new Guid("5a3d9c41-7f2b-4e8c-9c31-0fb28d74a922"),
                            ImageUrl = "https://www.autopower.bg/images/categories/75x75/%D0%9D%D0%B0%D0%BA%D0%BB%D0%B0%D0%B4%D0%BA%D0%B8.jpg",
                            Name = "Overlays"
                        },
                        new
                        {
                            Id = new Guid("6cd1f0b8-92b5-45a4-a6c1-3f84d9c2b7e0"),
                            CategoryId = new Guid("d4f0a8c7-12b9-4c53-8d77-61f4b3e2c915"),
                            ImageUrl = "https://www.autopower.bg/images/categories/75x75/%D0%90%D0%BD%D0%B3%D1%80%D0%B5%D0%BD%D0%B0%D0%B6%D0%BD%D0%B0%20%D0%B2%D0%B5%D1%80%D0%B8%D0%B3%D0%B0.png",
                            Name = "Timing Chain"
                        },
                        new
                        {
                            Id = new Guid("f29b31c4-0e52-4c7d-8b1f-9e4da37c1aa6"),
                            CategoryId = new Guid("d4f0a8c7-12b9-4c53-8d77-61f4b3e2c915"),
                            ImageUrl = "https://www.autopower.bg/images/categories/75x75/EGR%20%D0%BA%D0%BB%D0%B0%D0%BF%D0%B0%D0%BD.png",
                            Name = "EGR valve"
                        });
                });

            modelBuilder.Entity("GrandLineAuto.Data.Models.UserEntities.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("GrandLineAuto.Data.Models.UserEntities.UserProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Identification of the user profile");

                    b.Property<string>("City")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("DefaultAddress")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasComment("First name used for cheackout");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasComment("Last name used for checkout");

                    b.Property<string>("Phone")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Identification of the user id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserProfiles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("GrandLineAuto.Data.Models.BrandModelProductJoinTable", b =>
                {
                    b.HasOne("GrandLineAuto.Data.Models.BrandModels", "BrandModels")
                        .WithMany("BrandModelsProducts")
                        .HasForeignKey("BrandModelId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("GrandLineAuto.Data.Models.Product", "Products")
                        .WithMany("BrandModelsProducts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BrandModels");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("GrandLineAuto.Data.Models.BrandModels", b =>
                {
                    b.HasOne("GrandLineAuto.Data.Models.BrandModelsSeries", "BrandModelsSeries")
                        .WithMany("BrandModels")
                        .HasForeignKey("BrandModelsSeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BrandModelsSeries");
                });

            modelBuilder.Entity("GrandLineAuto.Data.Models.BrandModelsSeries", b =>
                {
                    b.HasOne("GrandLineAuto.Data.Models.Brand", "Brand")
                        .WithMany("BrandModelsSeries")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("GrandLineAuto.Data.Models.CartEntities.CartItem", b =>
                {
                    b.HasOne("GrandLineAuto.Data.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GrandLineAuto.Data.Models.UserEntities.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GrandLineAuto.Data.Models.OrderEntities.Order", b =>
                {
                    b.HasOne("GrandLineAuto.Data.Models.UserEntities.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GrandLineAuto.Data.Models.OrderEntities.OrderItem", b =>
                {
                    b.HasOne("GrandLineAuto.Data.Models.OrderEntities.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GrandLineAuto.Data.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("GrandLineAuto.Data.Models.OrderEntities.ShippingAddress", b =>
                {
                    b.HasOne("GrandLineAuto.Data.Models.OrderEntities.Order", "Order")
                        .WithOne("ShippingAddress")
                        .HasForeignKey("GrandLineAuto.Data.Models.OrderEntities.ShippingAddress", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("GrandLineAuto.Data.Models.Product", b =>
                {
                    b.HasOne("GrandLineAuto.Data.Models.ProductManufacturer", "ProductManufacturer")
                        .WithMany("Products")
                        .HasForeignKey("ProductManufacturerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GrandLineAuto.Data.Models.SubCategory", "SubCategory")
                        .WithMany("Products")
                        .HasForeignKey("SubCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductManufacturer");

                    b.Navigation("SubCategory");
                });

            modelBuilder.Entity("GrandLineAuto.Data.Models.SubCategory", b =>
                {
                    b.HasOne("GrandLineAuto.Data.Models.Category", "Category")
                        .WithMany("subCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("GrandLineAuto.Data.Models.UserEntities.UserProfile", b =>
                {
                    b.HasOne("GrandLineAuto.Data.Models.UserEntities.ApplicationUser", "User")
                        .WithOne("UserProfile")
                        .HasForeignKey("GrandLineAuto.Data.Models.UserEntities.UserProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("GrandLineAuto.Data.Models.UserEntities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("GrandLineAuto.Data.Models.UserEntities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GrandLineAuto.Data.Models.UserEntities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("GrandLineAuto.Data.Models.UserEntities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GrandLineAuto.Data.Models.Brand", b =>
                {
                    b.Navigation("BrandModelsSeries");
                });

            modelBuilder.Entity("GrandLineAuto.Data.Models.BrandModels", b =>
                {
                    b.Navigation("BrandModelsProducts");
                });

            modelBuilder.Entity("GrandLineAuto.Data.Models.BrandModelsSeries", b =>
                {
                    b.Navigation("BrandModels");
                });

            modelBuilder.Entity("GrandLineAuto.Data.Models.Category", b =>
                {
                    b.Navigation("subCategories");
                });

            modelBuilder.Entity("GrandLineAuto.Data.Models.OrderEntities.Order", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("ShippingAddress")
                        .IsRequired();
                });

            modelBuilder.Entity("GrandLineAuto.Data.Models.Product", b =>
                {
                    b.Navigation("BrandModelsProducts");
                });

            modelBuilder.Entity("GrandLineAuto.Data.Models.ProductManufacturer", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("GrandLineAuto.Data.Models.SubCategory", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("GrandLineAuto.Data.Models.UserEntities.ApplicationUser", b =>
                {
                    b.Navigation("UserProfile")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
